version: "3"
services:
  minecraft:
    image: umiqlo/paper-spigot-mc
    container_name: minecraft
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
    volumes:
      - './minecraft_data/:/opt/paper-spigot-mc'
    restart: always